### ISSUE TITLE
 WebRTC header does not compile in MSVC conformance mode (/permissive-)

### ISSUE THREAD

**Issue by fiban-havok** [microsoft/winrtc#15]
When compiling a VS 2019 project including api\video_codecs\video_encoder.h from m80 with the `/permissive-` option, the included header absl\container\internal\compressed_tuple.h fails to compile. 

This seems to be a VS bug and it's fixed in the preview: https://developercommunity.visualstudio.com/content/problem/841781/error-c3546-there-are-no-parameter-packs-available-1.html

We should point this out in the docs and/or suggest a minimum VS version.

**Comment by LoadLibrary** [comment]
Will `/permissive-` work with VS 2019 16.6.2?
