### ISSUE TITLE
Make C++17 optional when building WebRTC

### ISSUE THREAD

**Issue by fiban-havok** [microsoft/winrtc#19]
https://github.com/microsoft/winrtc/blob/master/patches_for_WebRTC_org/m80/0000-WebRTC-doesn-t-need-C-CX.patch enables C++17 unconditionally for UWP builds, for the sake of facilitating integration with WinRT/C++ code.

Google is building everything with C++14 AFAIK. There are issues in mixing C++17 and earlier when including/linking webrtc.lib, some absl classes are defined to std ones when C++17 is enabled and will make linking fail. Also building UWP with C++17 and Windows Desktop with C++14 has the potential to be a source of mistakes/inconsistencies.

Since C++17 is not strictly necessary on UWP it should at least be made optional. E.g. the line that uses it can be moved in a different patch to be applied optionally.

**Comment by gaspardpetit** [comment]
I can confirm that I was hit by this issue. The README should at least mention that the host project needs to use c++17, or else there are structures like abseil's `optional` that end up with a different size (native version is used under c++17 vs custom version under c++14).
