### ISSUE TITLE
Is the Media Foundation H264 encoder going to be part of this project?

### ISSUE THREAD

**Issue by Holo-Krzysztof** [microsoft/winrtc#30]
**Is your feature request related to a problem? Please describe.**
We're currently using `webrtc-uwp-sdk` and its windows-specific bits in a project that needs hardware-accelerated encoding and decoding. I've seen the issue for importing the decoder already and wanted to ask if the encoder is going to be imported into this project as well.

It'd be nice if we could upgrade to a newer WebRTC version because I'd like to test the new Insertable Streams API.

**Comment by LoadLibrary** [comment]
Thanks for using webrtc-uwp! :)

I'm currently working on bringing hardware accelerated end-to-end (camera + encoder/decoder H264) into WinRTC. It should land by June/July.

Upgrading to m83+ is on the books, but we're focusing on hardware accelerated features at this moment.

**Comment by LoadLibrary** [comment]
FYI, https://github.com/microsoft/winrtc/tree/master/patches_for_WebRTC_org/m84 has the H264 encoder/decoder from the WebRTC-UWP on top of the WebRTC m84.
