### ISSUE TITLE
Not able to compile MyFirstWinRtc solution

### ISSUE THREAD

**Issue by thiago-tota** [microsoft/winrtc#33]
**Describe the bug**
When trying to compile the solution I'm getting the following error message: "Cannot open include file: 'api/media_stream_interface.h': No such file or directory Microsoft.WinRtc.Simple.VideoConferencing"

**To Reproduce**
Steps to reproduce the behaviour:
1. Download source code from master branch
2. Open solution MyFirstWinRtc
3. Rebuild solution

**Expected behaviour**
Compile successfully.

**Screenshots**
![image](https://user-images.githubusercontent.com/30416982/84482991-f72ab880-ac98-11ea-91e7-5a62739382a4.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Visual Studio 2019 V16.6.2

**Comment by LoadLibrary** [comment]
Did you build WebRTC.lib locally? You'll find the steps for building libWebRTC at https://github.com/microsoft/winrtc/tree/master/patches_for_WebRTC_org/m80 . 
A NuGet package with WebRTC.lib is in the oven. We're clearing some legal requirements before making it public.

**Comment by thiago-tota** [comment]
I didn't, missed this step.
I'll do it, I'm closing the issue.
Thank you.
