### ISSUE TITLE
Wrong rtc_base/platform_thread_types.cc patch for m84

### ISSUE THREAD

**Issue by fiban-havok** [microsoft/winrtc#43]
The patch at `patches_for_WebRTC_org\m84\3001-Removing-code-that-only-runs-on-Win32-from-the-build.patch` doesn't apply to rtc_base/platform_thread_types.cc on the m84 branch - the corresponding code is significantly different.

Removing that part of the patch makes the patch go through. libwebrtc builds for UWP (x64 Debug at least) after that, but I am not sure if the unpatched code actually works as intended on UWP too.

**Comment by LoadLibrary** [comment]
Thanks for reporting it. We'll investigate momentarily.

**Comment by LoadLibrary** [comment]
The `3001-Removing-code-that-only-runs-on-Win32-from-the-build.patch` patch file has a fix for the following change that didn't land in the `branch-heads/4147` yet.

```
commit cf84607875d5dd13e33dddf33cf457d9a5f25e2c
Author: Tommi <tommi@webrtc.org>
Date:   Sun May 17 14:51:10 2020 +0200

    Reland "Use Windows 10 thread naming API"

    This reverts commit d0d55515c4b88a07446bc66a5c183f50ee896282.

    Reason for revert: Relanding with workaround.
```

I will update the patch and wait for `cf84607875d5dd13e33dddf33cf457d9a5f25e2c` to merge.

**Comment by LoadLibrary** [comment]
I've figured out the root cause of this issue. I was using `gclient sync` without the revision parameter. This was bringing code that didn't land in the m84 branch yet. I'm going to change my process in favor of using `gclient sync -D -r branch-heads/4147` instead.
