### ISSUE TITLE
Support MF H.264 and VP8/VP9 in the same PeerConnection

### ISSUE THREAD

**Issue by fiban-havok** [microsoft/winrtc#51]
At the moment the only way to use MF H.264 is to pass specific codec factories to the PeerConnectionFactory initialization. This means that you can't mix MF H.264 and other codecs, since there is no factory supporting both. 

It should be easy enough to make a proxy factory forwarding to either the MF H.264 one or the default one depending on the codec requested. This is what WebRTC-UWP used to do AFAIK (so this is technically a regression).

**Comment by LoadLibrary** [comment]
Sure thing.

> This is what WebRTC-UWP used to do AFAIK

The H264 factory code of WinRTC is the same as the WebRTC-UWP. As you can see in the original code (https://github.com/webrtc-uwp/webrtc-windows/blob/releases/m71/third_party/winuwp_h264/winuwp_h264_factory.cc), the factory did not forward codec construction.
