### ISSUE TITLE
Road map?

### ISSUE THREAD

**Issue by Holo-Viktor** [microsoft/winrtc#53]
Could you share a road map or a list of regressions/missing features?

**Comment by dayman40** [comment]
Hi @Holo-Viktor, thank you for being interested in WinRTC. The following is a regression list of WinRTC’s features that we currently have in our roadmap moving forward:
•	First in class XAML component
•	High performance audio and video experience. (Zero copy frames - increases battery life and CPU/GPU budgets in HL2)
•	WinRT APIs for AI and IoT use cases
•	Signaling code using SignalR
•	Improving GitHub pages
•	NuGet packages for all the 3 layers, API sets (UWP and Win32) and architectures (x64, ARM64 and x86)  
•	New encoders (H265, AV1)
•	Keep the security bar high (constant updates)

Please let us know if you have any question!

Thanks.

**Comment by LoadLibrary** [comment]
Closing as an answered question.
