### ISSUE TITLE
Question: How to build nuget package from source

### ISSUE THREAD

**Issue by RamadanAhmed** [microsoft/winrtc#89]
Hi all, 

Thanks for this great project. I managed to build webrtc project with patches, but I couldn't find documentation to build nuget packages to ease development to be able to work with sample project. So if you could provide such documentation it will be great

**Comment by SonOfJesseAsSnekithan** [comment]
I am having the same problem, I did build the webrtc project with patches, now I am trying to build Microsoft.WinRTC.Simple.VideoConferencing project, but i could not able to. Any help would be greatly appreciated.
Thanks

**Comment by osaghaso** [comment]
I apologies for the late reply.

You can get the Nuget on NuGet.org or visual studio.

How to install NuGet using visual studio.

In visual studio, click on Tools
Navigate to NuGet Package Manager
Click on Manage Package for Solution,
On Manage Package for Solution tab, click on browse
Then search for "Microsoft.WinRTC.libwebrtc.uwp"
then click on install.
Do the same for the NuGet Microsoft.Windows.CppWinRT and Microsoft.Win2D.

You can remove or comment this out from you Microsoft.WinRTC.Simple.VideoConferencing.vcxproj
`<Import Project="..\..\..\webrtc\src\out\msvc\uwp\Release\x64\packages\Microsoft.Windows.CppWinRT.2.0.200703.9\build\native\Microsoft.Windows.CppWinRT.props" Condition="Exists('..\..\..\webrtc\src\out\msvc\uwp\Release\x64\packages\Microsoft.Windows.CppWinRT.2.0.200703.9\build\native\Microsoft.Windows.CppWinRT.props')" />`

Also remove or comment out the " ......\webrtc\src\out" from your Microsoft.WinRTC.Simple.VideoConferencing.vcxproj as well.

Please let me know that if everything went good.

**Comment by SonOfJesseAsSnekithan** [comment]
I think I have tried something similar and was able to build, it worked.
Thanks anyway.
