### ISSUE TITLE
Question: [your question here] Is the NuGet package still available?

### ISSUE THREAD

**Issue by avrionov** [microsoft/winrtc#93]
I'm getting the following problem when I try to compile VideoConferencing project:

Package 'Microsoft.WinRTC.libwebrtc.84.0.13000001-alpha' is not found on source

**Comment by osaghaso** [comment]
Yes, its Available now.

How to install NuGet.

In visual studio, click on Tools,
Navigate to NuGet Package Manager,
Click on Manage Package for Solution,
On Manage Package for Solution tab, click on browse,
Then search for "Microsoft.WinRTC.libwebrtc.uwp",
Then click on install.

Do the same for the NuGet Microsoft.Windows.CppWinRT and Microsoft.Win2D.

You can remove or comment this out from you Microsoft.WinRTC.Simple.VideoConferencing.vcxproj
`<Import Project="..\..\..\webrtc\src\out\msvc\uwp\Release\x64\packages\Microsoft.Windows.CppWinRT.2.0.200703.9\build\native\Microsoft.Windows.CppWinRT.props" Condition="Exists('..\..\..\webrtc\src\out\msvc\uwp\Release\x64\packages\Microsoft.Windows.CppWinRT.2.0.200703.9\build\native\Microsoft.Windows.CppWinRT.props')" />`

Also remove or comment out the " ......\webrtc\src\out" from your Microsoft.WinRTC.Simple.VideoConferencing.vcxproj as well.

Please let me know that if everything went good.
