### ISSUE TITLE
Question: Missing packages after succesful build 

### ISSUE THREAD

**Issue by 0gnj3n** [microsoft/winrtc#97]
Greetings,

1. I have successfully build all.sln after applying patch M84. (no errors, tried twice, ninja and VS2019, followed steps to the letter)
2. I have opened VideoConferencing.sln and both sample projects loaded successfully. 
3. After a while I saw that paths in projects were configured for winrtc project to be on the same hierarchical level as webrtc project folder. I assured that that is the case.
4. I see that some folders and nuget packets are missing, packages are not being able to be restored.
5. There is no C:\webrtc\src\out\msvc\uwp\Release\x64\ **_packages_** folder

![image](https://user-images.githubusercontent.com/23733833/99036732-7d1d9900-2582-11eb-98c3-05b80c65fe7c.png)

as required in project file for multiple files, example

` <Import Project="..\..\..\webrtc\src\out\msvc\uwp\Release\x64\packages\Microsoft.Windows.CppWinRT.2.0.200703.9\build\native\Microsoft.Windows.CppWinRT.props" Condition="Exists('..\..\..\webrtc\src\out\msvc\uwp\Release\x64\packages\Microsoft.Windows.CppWinRT.2.0.200703.9\build\native\Microsoft.Windows.CppWinRT.props')" />`

6. There is no \packages\Microsoft.WinRTC.libwebrtc.84.0.13000001-alpha\build\native\Microsoft.WinRTC.libwebrtc.props in Samples directory as required in VideoConferencing project.

As I can see something is wrong with paths in Microsoft.WinRTC.libwebrtc.uwp.nuspec. It seams that package,cmd in .pipelines directory never executes + paths are wrong.

Am I missing something? 

Thank you in advance.

**Comment by osaghaso** [comment]
Hello, 

Apologies for the last reply.

Packages are not suppose to be in the  C:\webrtc\src\out\msvc\uwp\Release\x64\packages. You will get the packages folder once you install the NuGet need. It will be installed in "MyFirstWinRtc\VideoConferencing\packages\".

How to install NuGet.
1. In visual studio, click on Tools 
2. Navigate to NuGet Package Manager 
3. Click on Manage Package for Solution,
4. On Manage Package for Solution tab, click on browse
5. Then search for "Microsoft.WinRTC.libwebrtc.uwp"
6. then click on install.

Do the same for the NuGet Microsoft.Windows.CppWinRT and Microsoft.Win2D.

You can remove or comment this out from you Microsoft.WinRTC.Simple.VideoConferencing.vcxproj 
`
<Import Project="..\..\..\webrtc\src\out\msvc\uwp\Release\x64\packages\Microsoft.Windows.CppWinRT.2.0.200703.9\build\native\Microsoft.Windows.CppWinRT.props" Condition="Exists('..\..\..\webrtc\src\out\msvc\uwp\Release\x64\packages\Microsoft.Windows.CppWinRT.2.0.200703.9\build\native\Microsoft.Windows.CppWinRT.props')" />`


Also remove or comment out the " ..\..\..\webrtc\src\out" from your Microsoft.WinRTC.Simple.VideoConferencing.vcxproj as well.

Please let me know that if everything went good.
